services:
  bot:
    build: .
    container_name: grabhive-bot
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - default
      - socrates_network
    restart: unless-stopped

networks:
  socrates_network:
    external: true
    name: botsocrates_default
